apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: akto-envoy-filter
  namespace: default
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
    # you can use more sophisticated match conditions to apply akto envoy filter.
      listener:
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.filters.http.lua
       typed_config:
          "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
          defaultSourceCode:
            inlineString: |
              function aktoProcess()
                local aktoModule = require("aktoModule")
                aktoModule.sendToAkto()
              end
              
              -- this is a protected call. It catches any errors during function call.
              pcall(aktoProcess)
